---
# control

control:
  data_name: CIFAR10
  model_name: cnn
  task_name: 'fedavg'
  relu_threshold: '0'
  batch_size: '100'
  # for resnet: n, c, h, w / next layer: n, c_out, d_width, d_height
  # for gpt: n, s, d_h / next layer: n, s, d_h, q_length
  # w-pq-l1-0.2 / h-l1-0.2
  prune_method: w-pq-l1-0.2-2#3#4-max
  # inter / union / full_2-3-4_max / cas
  batch_integ: inter / union / full
  # somealgo-3
  multibatch_integ: somemethods-intmutiples
  
  # 如何快速算出计算量,
  
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
world_size: 1
resume_mode: 0
verbose: False