---
# control
control:
  data_name: fpb-sa
  model_name: bart
  task_name: s2s
  batch_size: 8
  seq_len: 128
  prune_metric: l1+128
  prune_name: pq-0.7-0.7+w+0.2+2#3#4
  cust_tgt_modules: None
  # batch_integ: inter
  # multibatch_integ: somemethods-3
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
world_size: 1
resume_mode: 0
verbose: False


# python verify.py --control_name fpb-sa_test_s2s_8_pq-h-1-0.2-1#2-max_inter_somemethods-3