sbatch csr0boolq_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0boolq_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0boolq_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0boolq_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0boolq_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0boolq_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0piqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0piqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0piqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0piqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0piqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0piqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0hellaswag_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0hellaswag_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0hellaswag_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0hellaswag_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0hellaswag_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0hellaswag_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0winogrande_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0winogrande_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0winogrande_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0winogrande_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0winogrande_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0winogrande_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-c_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-c_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-c_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-c_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-c_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-c_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-e_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-e_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-e_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-e_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-e_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0arc-e_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0obqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0obqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0obqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0obqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr0obqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr0obqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1boolq_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1boolq_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1boolq_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1boolq_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1boolq_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1boolq_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1piqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1piqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1piqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1piqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1piqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1piqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1hellaswag_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1hellaswag_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1hellaswag_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1hellaswag_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1hellaswag_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1hellaswag_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1winogrande_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1winogrande_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1winogrande_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1winogrande_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1winogrande_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1winogrande_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-c_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-c_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-c_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-c_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-c_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-c_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-e_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-e_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-e_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-e_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-e_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1arc-e_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1obqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1obqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1obqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1obqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr1obqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr1obqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2boolq_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2boolq_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2boolq_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2boolq_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2boolq_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2boolq_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2piqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2piqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2piqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2piqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2piqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2piqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2hellaswag_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2hellaswag_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2hellaswag_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2hellaswag_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2hellaswag_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2hellaswag_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2winogrande_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2winogrande_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2winogrande_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2winogrande_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2winogrande_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2winogrande_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-c_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-c_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-c_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-c_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-c_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-c_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-e_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-e_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-e_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-e_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-e_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2arc-e_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2obqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2obqa_llama-2-7b_csr_20_512_0.2_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2obqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2obqa_llama-2-7b_csr_20_512_0.4_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
sbatch csr2obqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-prune_asyncinter_None_None_None.pbs --wait
sbatch csr2obqa_llama-2-7b_csr_20_512_0.6_None_llmpruner-tune_asyncinter_None_None_None.pbs --wait
